query GetElectedCouncils(
  $where: ElectedCouncilWhereInput
  $orderBy: [ElectedCouncilOrderByInput!]
  $offset: Int
  $limit: Int
) {
  electedCouncils(where: $where, orderBy: $orderBy, offset: $offset, limit: $limit) {
    ...ElectedCouncilFields
    __typename
  }
}

fragment ElectedCouncilFields on ElectedCouncil {
  id
  electedAtBlock
  endedAtBlock
  electedAtTime
  endedAtTime
  electedAtNetwork
  endedAtNetwork
  councilElections {
    cycleId
  }
  councilMembers {
    ...CouncilMemberFields
  }
}

fragment CouncilMemberFields on CouncilMember {
  id
  member {
    ...MemberFields
    councilMembers {
      __typename
    }
    __typename
  }
  unpaidReward
  stake
  __typename
}

fragment MemberFields on Membership {
  id
  rootAccount
  controllerAccount
  boundAccounts
  handle
  metadata {
    name
    about
    avatar {
      __typename
      ... on AvatarUri {
        avatarUri
        __typename
      }
    }
    __typename
  }
  isVerified
  isFoundingMember
  isCouncilMember
  inviteCount
  roles {
    id
    group {
      name
      __typename
    }
    createdAt
    isLead
    __typename
  }
  createdAt
  stakingaccountaddedeventmember {
    createdAt
    inBlock
    network
    account
    __typename
  }
  __typename
}
